---
version: '3.9'
services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn test --collect-coverage'
  build:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn build'
  lint:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn lint:app'
  lint-yaml:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yamllint --strict .'
